# Generated by Django 3.2.8 on 2021-11-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=250)),
                ('submited_by', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=250)),
                ('file_type', models.CharField(max_length=250)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=250)),
                ('submited_by', models.CharField(max_length=250)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='myCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.semester'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.course'),
        ),
    ]
