# Generated by Django 3.2.8 on 2021-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_singn_up'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='singn_up',
            new_name='sign_up',
        ),
    ]
