# Generated by Django 3.2.8 on 2021-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0006_rename_singn_up_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='%m/%d/%y')),
            ],
        ),
    ]
